# Generated by Django 5.2.16 on 2026-07-29 20:25

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def enable_rls(_apps, schema_editor) -> None:
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            'ALTER TABLE public."imports_catalogimportbatch" ENABLE ROW LEVEL SECURITY;'
        )
        schema_editor.execute(
            'ALTER TABLE public."imports_catalogimportdraft" ENABLE ROW LEVEL SECURITY;'
        )


def disable_rls(_apps, schema_editor) -> None:
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            'ALTER TABLE public."imports_catalogimportdraft" DISABLE ROW LEVEL SECURITY;'
        )
        schema_editor.execute(
            'ALTER TABLE public."imports_catalogimportbatch" DISABLE ROW LEVEL SECURITY;'
        )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0002_external_discovery"),
        ("regions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "idempotency_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("byte_size", models.PositiveBigIntegerField()),
                ("row_count", models.PositiveIntegerField()),
                ("warning_count", models.PositiveIntegerField(default=0)),
                ("create_count", models.PositiveIntegerField(default=0)),
                ("update_count", models.PositiveIntegerField(default=0)),
                ("archive_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("committed", "Confirmado")],
                        db_index=True,
                        default="committed",
                        max_length=16,
                    ),
                ),
                (
                    "committed_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-committed_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="CatalogImportDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_number", models.PositiveIntegerField()),
                ("external_id", models.CharField(max_length=160)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("create", "Criar"),
                            ("update", "Atualizar"),
                            ("archive", "Arquivar"),
                        ],
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Rascunho")],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drafts",
                        to="imports.catalogimportbatch",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_import_drafts",
                        to="regions.region",
                    ),
                ),
                (
                    "target_actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_import_drafts",
                        to="catalog.actor",
                    ),
                ),
            ],
            options={
                "ordering": ("batch_id", "line_number"),
            },
        ),
        migrations.AddIndex(
            model_name="catalogimportbatch",
            index=models.Index(
                fields=["created_by", "committed_at"],
                name="import_batch_author_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="catalogimportdraft",
            index=models.Index(fields=["region", "status"], name="import_draft_region_state_idx"),
        ),
        migrations.AddIndex(
            model_name="catalogimportdraft",
            index=models.Index(
                fields=["target_actor", "status"], name="import_draft_actor_state_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogimportdraft",
            constraint=models.UniqueConstraint(
                fields=("batch", "line_number"), name="import_draft_batch_line_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogimportdraft",
            constraint=models.UniqueConstraint(
                fields=("batch", "external_id"), name="import_draft_batch_external_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogimportdraft",
            constraint=models.CheckConstraint(
                condition=models.Q(("line_number__gte", 2)),
                name="import_draft_line_valid",
            ),
        ),
        migrations.RunPython(enable_rls, disable_rls),
    ]
