# Generated by Django 5.2.16 on 2026-07-29 19:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def enable_rls(_apps, schema_editor) -> None:
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute('ALTER TABLE public."audit_auditevent" ENABLE ROW LEVEL SECURITY;')


def disable_rls(_apps, schema_editor) -> None:
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute('ALTER TABLE public."audit_auditevent" DISABLE ROW LEVEL SECURITY;')


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("regions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("auth.login", "Login administrativo"),
                            ("auth.logout", "Logout administrativo"),
                            ("editorial.approve", "Aprovação editorial"),
                            ("publication.publish", "Publicação"),
                            ("publication.restore", "Restauração"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("target_type", models.CharField(max_length=64)),
                ("target_id", models.CharField(max_length=128)),
                ("request_id", models.UUIDField(db_index=True)),
                ("reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "result",
                    models.CharField(
                        choices=[("success", "Sucesso")],
                        default="success",
                        max_length=16,
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="administrative_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="administrative_audit_events",
                        to="regions.region",
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at", "-id"),
                "indexes": [
                    models.Index(fields=["actor", "occurred_at"], name="audit_actor_date_idx"),
                    models.Index(fields=["region", "occurred_at"], name="audit_region_date_idx"),
                    models.Index(fields=["action", "occurred_at"], name="audit_action_date_idx"),
                ],
            },
        ),
        migrations.RunPython(enable_rls, disable_rls),
    ]
