# Generated by Django 5.2.16 on 2026-07-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0002_alter_auditevent_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("auth.login", "Login administrativo"),
                    ("auth.logout", "Logout administrativo"),
                    ("editorial.approve", "Aprovação editorial"),
                    ("publication.publish", "Publicação"),
                    ("publication.restore", "Restauração"),
                    ("external.discovery", "Descoberta externa"),
                    ("import.commit", "Confirmação de importação"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
    ]
