# Generated by Django 5.2.16 on 2026-07-31 19:35

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("incorrect_info", "Informação Incorreta"),
                            ("closed_location", "Local Fechado ou Inacessível"),
                            ("wrong_contact", "Contato Desatualizado"),
                            ("safety_warning", "Alerta de Segurança"),
                            ("other", "Outro Assunto"),
                        ],
                        default="incorrect_info",
                        max_length=32,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("route", "Rota"),
                            ("actor", "Ator / Ponto Local"),
                            ("general", "Geral"),
                        ],
                        default="general",
                        max_length=32,
                    ),
                ),
                ("target_id", models.UUIDField(blank=True, null=True)),
                (
                    "target_slug",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "region_slug",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("description", models.TextField(max_length=1000)),
                (
                    "reporter_contact",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("reviewed", "Revisado"),
                            ("rejected", "Rejeitado"),
                            ("actioned", "Ação Concluída"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("moderation_note", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Relato Público",
                "verbose_name_plural": "Relatos Públicos",
                "ordering": ["-created_at"],
            },
        ),
    ]
