/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/admin/analytics/summary': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Visão resumida de analytics agregada para o painel administrativo.
     *     Protegido por autenticação e livre de identificadores individuais.
     */
    get: operations['api_v1_admin_analytics_summary_retrieve']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/audit-logs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['listAdminAuditEvents']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/auth/csrf': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getAdminCsrfToken']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['loginAdmin']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['logoutAdmin']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/auth/session': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getAdminSession']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/discovery/google-places/preview': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['previewGooglePlacesCandidates']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/editorial/publications/{publication_id}/restore': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['restorePublicationVersion']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/editorial/revisions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['createEditorialRevision']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/editorial/revisions/{revision_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['retrieveEditorialRevision']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: operations['updateEditorialRevision']
    trace?: never
  }
  '/api/v1/admin/editorial/revisions/{revision_id}/approve': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['approveEditorialRevision']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/editorial/revisions/{revision_id}/publish': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['publishEditorialRevision']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/editorial/revisions/{revision_id}/return': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['returnEditorialRevision']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/editorial/revisions/{revision_id}/submit': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['submitEditorialRevision']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/imports/commit': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['commitCatalogCsv']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/imports/validate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['validateCatalogCsv']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/reports/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description Lista relatos da comunidade para moderação e triagem. */
    get: operations['api_v1_admin_reports_list']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/reports/{report_id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** @description Atualiza o status de moderação e nota técnica de um relato. */
    patch: operations['api_v1_admin_reports_partial_update']
    trace?: never
  }
  '/api/v1/events/batch': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * @description Ingestão pública em lote de eventos de analytics pseudonimizados.
     *     Aplica allowlist estrita e rejeição de dados pessoais ou coordenadas.
     */
    post: operations['api_v1_events_batch_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['api_v1_health_retrieve']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/public/reports/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * @description Criação pública de relato de informação incorreta.
     *     Protegido contra autopublicação e abusos de tamanho.
     */
    post: operations['api_v1_public_reports_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/regions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Listar regiões publicadas
     * @description Retorna somente regiões disponíveis para navegação pública.
     */
    get: operations['listPublishedRegions']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/regions/{region_slug}/routes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Listar rotas publicadas de uma região */
    get: operations['listPublishedRegionRoutes']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/regions/{region_slug}/routes/{route_slug}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Obter uma rota publicada */
    get: operations['retrievePublishedRoute']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/regions/{region_slug}/routes/{route_slug}/catalog': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Listar o catálogo público contextual da rota
     * @description Retorna somente atores publicados, localizações visíveis na região e contatos autorizados para publicação.
     */
    get: operations['listPublishedRouteCatalog']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/schema/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
     *
     *     - YAML: application/vnd.oai.openapi
     *     - JSON: application/vnd.oai.openapi+json
     */
    get: operations['api_v1_schema_retrieve']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * @description * `auth.login` - Login administrativo
     *     * `auth.logout` - Logout administrativo
     *     * `editorial.approve` - Aprovação editorial
     *     * `publication.publish` - Publicação
     *     * `publication.restore` - Restauração
     *     * `external.discovery` - Descoberta externa
     *     * `import.commit` - Confirmação de importação
     *     * `report.moderate` - Moderação de relato
     * @enum {string}
     */
    ActionEnum:
      | 'auth.login'
      | 'auth.logout'
      | 'editorial.approve'
      | 'publication.publish'
      | 'publication.restore'
      | 'external.discovery'
      | 'import.commit'
      | 'report.moderate'
    /**
     * @description * `business` - Empresa
     *     * `individual_provider` - Prestador individual
     *     * `community` - Comunidade
     *     * `institution` - Instituição
     *     * `support` - Ponto de apoio
     * @enum {string}
     */
    ActorKindEnum:
      | 'business'
      | 'individual_provider'
      | 'community'
      | 'institution'
      | 'support'
    AdminIdentity: {
      id: string
      username: string
      roles: string[]
      actions: string[]
      region_slugs: string[]
    }
    AdminReport: {
      /** Format: uuid */
      readonly id: string
      readonly report_type: components['schemas']['ReportTypeEnum']
      readonly target_type: components['schemas']['TargetTypeEf3Enum']
      /** Format: uuid */
      readonly target_id: string | null
      readonly target_slug: string
      readonly region_slug: string
      readonly description: string
      readonly reporter_contact: string
      status?: components['schemas']['AdminReportStatusEnum']
      moderation_note?: string
      /** Format: date-time */
      readonly created_at: string
      /** Format: date-time */
      readonly updated_at: string
    }
    /**
     * @description * `pending` - Pendente
     *     * `reviewed` - Revisado
     *     * `rejected` - Rejeitado
     *     * `actioned` - Ação Concluída
     * @enum {string}
     */
    AdminReportStatusEnum: 'pending' | 'reviewed' | 'rejected' | 'actioned'
    Alert: {
      /** Format: uuid */
      readonly id: string
      severity: components['schemas']['AlertSeverityEnum']
      title: string
      description: string
      alternative?: string
      /** Format: date-time */
      starts_at: string
      /** Format: date-time */
      ends_at?: string | null
      /** Format: date-time */
      readonly updated_at: string
    }
    /**
     * @description * `info` - Informativo
     *     * `warning` - Atenção
     *     * `critical` - Crítico
     * @enum {string}
     */
    AlertSeverityEnum: 'info' | 'warning' | 'critical'
    AnalyticsBatch: {
      events: components['schemas']['AnalyticsEventInput'][]
    }
    AnalyticsEventInput: {
      /** Format: uuid */
      readonly event_id: string
      event_name: string
      schema_version?: string
      /** Format: date-time */
      occurred_at: string
      /** Format: uuid */
      anonymous_id: string
      /** Format: uuid */
      session_id?: string | null
      /** Format: uuid */
      consent_id?: string | null
      consent_version?: string
      app_version?: string
      screen_name?: string
      region_id?: string
      route_id?: string
      actor_id?: string
      stage_id?: string
      source?: string
      campaign_id?: string
      device_class?: string
      network_class?: string
      display_mode?: string
      properties?: unknown
    }
    AuditEvent: {
      /** Format: uuid */
      readonly id: string
      readonly actor_id: string
      /** Format: uuid */
      readonly region_id: string | null
      readonly action: components['schemas']['ActionEnum']
      readonly target_type: string
      readonly target_id: string
      /** Format: uuid */
      readonly request_id: string
      readonly reason: string
      readonly metadata: unknown
      readonly result: components['schemas']['ResultEnum']
      /** Format: date-time */
      readonly occurred_at: string
    }
    CatalogCsvCommitRequest: {
      /** Format: uri */
      file: string
      sha256: string
      /** Format: uuid */
      idempotency_key: string
      confirmed: boolean
    }
    CatalogCsvIssue: {
      severity: components['schemas']['CatalogCsvIssueSeverityEnum']
      code: string
      line: number
      column: string | null
      message: string
    }
    /**
     * @description * `error` - error
     *     * `warning` - warning
     * @enum {string}
     */
    CatalogCsvIssueSeverityEnum: 'error' | 'warning'
    CatalogCsvPreview: {
      create_count: number
      update_count: number
      archive_count: number
      rows: components['schemas']['CatalogCsvPreviewRow'][]
    }
    CatalogCsvPreviewRow: {
      line: number
      external_id: string
      operation: components['schemas']['OperationEnum']
    }
    CatalogCsvValidationRequest: {
      /** Format: uri */
      file: string
    }
    CatalogCsvValidationResponse: {
      valid: boolean
      sha256: string
      row_count: number
      error_count: number
      warning_count: number
      issues_truncated: boolean
      issues: components['schemas']['CatalogCsvIssue'][]
      preview: components['schemas']['CatalogCsvPreview'] | null
    }
    CatalogImportCommitError: {
      code: string
      message: string
      field_errors: {
        [key: string]: string[]
      }
      /** Format: uuid */
      request_id: string
    }
    CatalogImportCommitResponse: {
      /** Format: uuid */
      id: string
      status: components['schemas']['CatalogImportCommitResponseStatusEnum']
      replayed: boolean
      sha256: string
      row_count: number
      warning_count: number
      create_count: number
      update_count: number
      archive_count: number
      /** Format: date-time */
      committed_at: string
    }
    /**
     * @description * `committed` - committed
     * @enum {string}
     */
    CatalogImportCommitResponseStatusEnum: 'committed'
    /**
     * @description * `phone` - Telefone
     *     * `whatsapp` - WhatsApp
     *     * `email` - E-mail
     *     * `website` - Site
     *     * `instagram` - Instagram
     * @enum {string}
     */
    ChannelTypeEnum: 'phone' | 'whatsapp' | 'email' | 'website' | 'instagram'
    CreateEditorialRevision: {
      target_type: components['schemas']['TargetTypeFdcEnum']
      /** Format: uuid */
      target_id: string
      /** Format: uuid */
      region_id?: string | null
      snapshot: unknown
    }
    CsrfResponse: {
      csrf_token: string
    }
    /**
     * @description * `easy` - Fácil
     *     * `moderate` - Moderada
     *     * `hard` - Difícil
     * @enum {string}
     */
    DifficultyEnum: 'easy' | 'moderate' | 'hard'
    EditorialRevision: {
      /** Format: uuid */
      readonly id: string
      /** Format: uuid */
      readonly region_id: string
      readonly target_type: components['schemas']['TargetTypeFdcEnum']
      /** Format: uuid */
      readonly target_id: string
      readonly sequence: number
      readonly status: components['schemas']['EditorialRevisionStatusEnum']
      readonly base_snapshot: unknown
      readonly snapshot: unknown
      readonly diff: unknown
      readonly lock_version: number
      readonly created_by_id: string
      readonly updated_by_id: string
      readonly submitted_by_id: string | null
      /** Format: date-time */
      readonly submitted_at: string | null
      readonly reviewed_by_id: string | null
      /** Format: date-time */
      readonly reviewed_at: string | null
      readonly return_reason: string
      /** Format: date-time */
      readonly created_at: string
      /** Format: date-time */
      readonly updated_at: string
    }
    /**
     * @description * `draft` - Rascunho
     *     * `review` - Em revisão
     *     * `approved` - Aprovado
     *     * `published` - Publicado
     * @enum {string}
     */
    EditorialRevisionStatusEnum: 'draft' | 'review' | 'approved' | 'published'
    EditorialWorkflowError: {
      code: string
      message: string
      field_errors: {
        [key: string]: string[]
      }
      /** Format: uuid */
      request_id: string
    }
    ExternalDiscoveryError: {
      code: string
      message: string
      field_errors: {
        [key: string]: string[]
      }
      /** Format: uuid */
      request_id: string
    }
    GooglePlacesCandidate: {
      place_id: string
      display_name: string
      formatted_address: string
      /** Format: double */
      latitude: number | null
      /** Format: double */
      longitude: number | null
      primary_type: string
      /** Format: uri */
      google_maps_uri: string
    }
    GooglePlacesPreviewRequest: {
      region_slug: string
      route_slug: string
      /** Format: double */
      latitude: number
      /** Format: double */
      longitude: number
      radius_meters: number
      included_types: string[]
      max_results: number
    }
    GooglePlacesPreviewResponse: {
      /** Format: uuid */
      run_id: string
      provider: string
      attribution: string
      result_count: number
      candidates: components['schemas']['GooglePlacesCandidate'][]
    }
    LoginRequest: {
      username: string
      password: string
    }
    OperatingHours: {
      weekday?: number | null
      /** Format: time */
      opens_at?: string | null
      /** Format: time */
      closes_at?: string | null
      is_closed?: boolean
      /** Format: date */
      exception_date?: string | null
      public_note?: string
    }
    /**
     * @description * `create` - create
     *     * `update` - update
     *     * `archive` - archive
     * @enum {string}
     */
    OperationEnum: 'create' | 'update' | 'archive'
    /**
     * @description * `editorial` - Editorial
     *     * `partner` - Parceiro
     *     * `sponsored` - Patrocinado
     * @enum {string}
     */
    PartnershipTypeEnum: 'editorial' | 'partner' | 'sponsored'
    PatchedAdminReport: {
      /** Format: uuid */
      readonly id?: string
      readonly report_type?: components['schemas']['ReportTypeEnum']
      readonly target_type?: components['schemas']['TargetTypeEf3Enum']
      /** Format: uuid */
      readonly target_id?: string | null
      readonly target_slug?: string
      readonly region_slug?: string
      readonly description?: string
      readonly reporter_contact?: string
      status?: components['schemas']['AdminReportStatusEnum']
      moderation_note?: string
      /** Format: date-time */
      readonly created_at?: string
      /** Format: date-time */
      readonly updated_at?: string
    }
    PatchedUpdateEditorialRevision: {
      snapshot?: unknown
      lock_version?: number
    }
    PublicActor: {
      /** Format: uuid */
      readonly id: string
      slug: string
      public_name: string
      actor_kind: components['schemas']['ActorKindEnum']
      short_description: string
      full_description?: string
      services?: unknown
      partnership_type?: components['schemas']['PartnershipTypeEnum']
      readonly category_slug: string
      readonly category_name: string
      readonly locations: components['schemas']['PublicActorLocation'][]
      readonly contact_channels: components['schemas']['PublicContactChannel'][]
      /** Format: date-time */
      readonly updated_at: string
    }
    PublicActorLocation: {
      label: string
      address_fields?: unknown
      readonly point: {
        /** @enum {string} */
        type: 'Point'
        coordinates: number[]
      } | null
      is_primary?: boolean
      readonly operating_hours: components['schemas']['OperatingHours'][]
      /** Format: date-time */
      readonly updated_at: string
    }
    PublicContactChannel: {
      channel_type: components['schemas']['ChannelTypeEnum']
      public_value?: string
      /** Format: date-time */
      verified_at?: string | null
    }
    PublicReportCreate: {
      /** Format: uuid */
      readonly id: string
      report_type?: components['schemas']['ReportTypeEnum']
      target_type?: components['schemas']['TargetTypeEf3Enum']
      /** Format: uuid */
      target_id?: string | null
      target_slug?: string
      region_slug?: string
      description: string
      reporter_contact?: string
      /** Format: date-time */
      readonly created_at: string
    }
    PublicReportCreatedResponse: {
      /** Format: uuid */
      id: string
      message: string
      status: string
    }
    PublicationVersion: {
      /** Format: uuid */
      readonly id: string
      /** Format: uuid */
      readonly revision_id: string | null
      /** Format: uuid */
      readonly restored_from_id: string | null
      /** Format: uuid */
      readonly region_id: string
      readonly target_type: components['schemas']['TargetTypeFdcEnum']
      /** Format: uuid */
      readonly target_id: string
      readonly version: number
      readonly snapshot: unknown
      readonly checksum: string
      readonly approved_by_id: string
      readonly published_by_id: string
      readonly reason: string
      readonly source_confirmed: boolean
      readonly human_confirmed: boolean
      readonly critical_information_current: boolean
      readonly critical_override_reason: string
      /** Format: date-time */
      readonly published_at: string
    }
    PublishEditorialRevision: {
      lock_version: number
      reason?: string
      source_confirmed: boolean
      human_confirmed: boolean
      critical_information_current: boolean
      critical_override_reason?: string
    }
    RegionSummary: {
      /** Format: uuid */
      readonly id: string
      slug: string
      public_name: string
      short_description?: string
      readonly center_point: {
        /** @enum {string} */
        type: 'Point'
        coordinates: number[]
      }
      timezone?: string
      published_version?: number | null
      /** Format: date-time */
      readonly updated_at: string
    }
    /**
     * @description * `incorrect_info` - Informação Incorreta
     *     * `closed_location` - Local Fechado ou Inacessível
     *     * `wrong_contact` - Contato Desatualizado
     *     * `safety_warning` - Alerta de Segurança
     *     * `other` - Outro Assunto
     * @enum {string}
     */
    ReportTypeEnum:
      | 'incorrect_info'
      | 'closed_location'
      | 'wrong_contact'
      | 'safety_warning'
      | 'other'
    RestorePublicationVersion: {
      expected_current_version: number
      reason: string
      source_confirmed: boolean
      human_confirmed: boolean
      critical_information_current: boolean
      critical_override_reason?: string
    }
    /**
     * @description * `success` - Sucesso
     * @enum {string}
     */
    ResultEnum: 'success'
    ReturnEditorialRevision: {
      lock_version: number
      reason: string
    }
    RevisionTransition: {
      lock_version: number
    }
    RouteCatalogItem: {
      route_role: components['schemas']['RouteRoleEnum']
      editorial_position?: number
      is_featured?: boolean
      sponsorship_label?: string
      /** Format: uuid */
      readonly stage_id: string | null
      readonly actor: components['schemas']['PublicActor']
    }
    RouteDetail: {
      /** Format: uuid */
      readonly id: string
      slug: string
      public_name: string
      short_promise: string
      duration_minutes: number
      difficulty: components['schemas']['DifficultyEnum']
      /** Format: decimal */
      estimated_cost_min?: string | null
      /** Format: decimal */
      estimated_cost_max?: string | null
      transport_modes?: unknown
      accessibility_content?: string
      offline_enabled?: boolean
      /** Format: date-time */
      readonly updated_at: string
      readonly region_slug: string
      readonly region_name: string
      description?: string
      preparation_content?: string
      readonly stages: components['schemas']['RouteStage'][]
      readonly segments: components['schemas']['RouteSegment'][]
      readonly alerts: components['schemas']['Alert'][]
    }
    /**
     * @description * `experience` - Experiência
     *     * `support` - Apoio
     *     * `start` - Início
     *     * `stop` - Parada
     *     * `emergency` - Emergência
     *     * `service` - Serviço
     * @enum {string}
     */
    RouteRoleEnum:
      'experience' | 'support' | 'start' | 'stop' | 'emergency' | 'service'
    RouteSegment: {
      /** Format: uuid */
      readonly id: string
      /** Format: uuid */
      readonly from_stage_id: string
      /** Format: uuid */
      readonly to_stage_id: string
      readonly geometry: {
        /** @enum {string} */
        type: 'LineString'
        coordinates: number[][]
      }
      transport_mode: string
      distance_meters: number
      duration_minutes: number
      instructions?: string
      /** Format: date-time */
      readonly updated_at: string
    }
    RouteStage: {
      /** Format: uuid */
      readonly id: string
      position: number
      public_name: string
      description?: string
      readonly point: {
        /** @enum {string} */
        type: 'Point'
        coordinates: number[]
      }
      arrival_guidance?: string
      duration_minutes?: number | null
      stage_type: components['schemas']['StageTypeEnum']
      is_optional?: boolean
      /** Format: date-time */
      readonly updated_at: string
    }
    RouteSummary: {
      /** Format: uuid */
      readonly id: string
      slug: string
      public_name: string
      short_promise: string
      duration_minutes: number
      difficulty: components['schemas']['DifficultyEnum']
      /** Format: decimal */
      estimated_cost_min?: string | null
      /** Format: decimal */
      estimated_cost_max?: string | null
      transport_modes?: unknown
      accessibility_content?: string
      offline_enabled?: boolean
      /** Format: date-time */
      readonly updated_at: string
    }
    SessionResponse: {
      authenticated: boolean
      user: components['schemas']['AdminIdentity'] | null
    }
    /**
     * @description * `start` - Início
     *     * `stop` - Parada
     *     * `experience` - Experiência
     *     * `support` - Apoio
     *     * `end` - Fim
     * @enum {string}
     */
    StageTypeEnum: 'start' | 'stop' | 'experience' | 'support' | 'end'
    /**
     * @description * `route` - Rota
     *     * `actor` - Ator / Ponto Local
     *     * `general` - Geral
     * @enum {string}
     */
    TargetTypeEf3Enum: 'route' | 'actor' | 'general'
    /**
     * @description * `region` - Região
     *     * `route` - Rota
     *     * `actor` - Ator
     * @enum {string}
     */
    TargetTypeFdcEnum: 'region' | 'route' | 'actor'
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  api_v1_admin_analytics_summary_retrieve: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            total_events?: number
            aggregates?: {
              date?: string
              event_name?: string
              region_slug?: string
              route_slug?: string
              count?: number
            }[]
          }
        }
      }
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            detail?: string
          }
        }
      }
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            detail?: string
          }
        }
      }
    }
  }
  listAdminAuditEvents: {
    parameters: {
      query?: {
        /**
         * @description * `auth.login` - Login administrativo
         *     * `auth.logout` - Logout administrativo
         *     * `editorial.approve` - Aprovação editorial
         *     * `publication.publish` - Publicação
         *     * `publication.restore` - Restauração
         *     * `external.discovery` - Descoberta externa
         *     * `import.commit` - Confirmação de importação
         *     * `report.moderate` - Moderação de relato
         */
        action?:
          | 'auth.login'
          | 'auth.logout'
          | 'editorial.approve'
          | 'publication.publish'
          | 'publication.restore'
          | 'external.discovery'
          | 'import.commit'
          | 'report.moderate'
        limit?: number
        offset?: number
        region_id?: string
        target_id?: string
        target_type?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuditEvent'][]
        }
      }
    }
  }
  getAdminCsrfToken: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CsrfResponse']
        }
      }
    }
  }
  loginAdmin: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
        'application/x-www-form-urlencoded': components['schemas']['LoginRequest']
        'multipart/form-data': components['schemas']['LoginRequest']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SessionResponse']
        }
      }
    }
  }
  logoutAdmin: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SessionResponse']
        }
      }
    }
  }
  getAdminSession: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SessionResponse']
        }
      }
    }
  }
  previewGooglePlacesCandidates: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['GooglePlacesPreviewRequest']
        'application/x-www-form-urlencoded': components['schemas']['GooglePlacesPreviewRequest']
        'multipart/form-data': components['schemas']['GooglePlacesPreviewRequest']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GooglePlacesPreviewResponse']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExternalDiscoveryError']
        }
      }
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExternalDiscoveryError']
        }
      }
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExternalDiscoveryError']
        }
      }
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExternalDiscoveryError']
        }
      }
    }
  }
  restorePublicationVersion: {
    parameters: {
      query?: never
      header?: never
      path: {
        publication_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RestorePublicationVersion']
        'application/x-www-form-urlencoded': components['schemas']['RestorePublicationVersion']
        'multipart/form-data': components['schemas']['RestorePublicationVersion']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PublicationVersion']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EditorialWorkflowError']
        }
      }
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EditorialWorkflowError']
        }
      }
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EditorialWorkflowError']
        }
      }
    }
  }
  createEditorialRevision: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateEditorialRevision']
        'application/x-www-form-urlencoded': components['schemas']['CreateEditorialRevision']
        'multipart/form-data': components['schemas']['CreateEditorialRevision']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EditorialRevision']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EditorialWorkflowError']
        }
      }
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EditorialWorkflowError']
        }
      }
    }
  }
  retrieveEditorialRevision: {
    parameters: {
      query?: never
      header?: never
      path: {
        revision_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EditorialRevision']
        }
      }
    }
  }
  updateEditorialRevision: {
    parameters: {
      query?: never
      header?: never
      path: {
        revision_id: string
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedUpdateEditorialRevision']
        'application/x-www-form-urlencoded': components['schemas']['PatchedUpdateEditorialRevision']
        'multipart/form-data': components['schemas']['PatchedUpdateEditorialRevision']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EditorialRevision']
        }
      }
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EditorialWorkflowError']
        }
      }
    }
  }
  approveEditorialRevision: {
    parameters: {
      query?: never
      header?: never
      path: {
        revision_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RevisionTransition']
        'application/x-www-form-urlencoded': components['schemas']['RevisionTransition']
        'multipart/form-data': components['schemas']['RevisionTransition']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EditorialRevision']
        }
      }
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EditorialWorkflowError']
        }
      }
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EditorialWorkflowError']
        }
      }
    }
  }
  publishEditorialRevision: {
    parameters: {
      query?: never
      header?: never
      path: {
        revision_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PublishEditorialRevision']
        'application/x-www-form-urlencoded': components['schemas']['PublishEditorialRevision']
        'multipart/form-data': components['schemas']['PublishEditorialRevision']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PublicationVersion']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EditorialWorkflowError']
        }
      }
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EditorialWorkflowError']
        }
      }
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EditorialWorkflowError']
        }
      }
    }
  }
  returnEditorialRevision: {
    parameters: {
      query?: never
      header?: never
      path: {
        revision_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ReturnEditorialRevision']
        'application/x-www-form-urlencoded': components['schemas']['ReturnEditorialRevision']
        'multipart/form-data': components['schemas']['ReturnEditorialRevision']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EditorialRevision']
        }
      }
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EditorialWorkflowError']
        }
      }
    }
  }
  submitEditorialRevision: {
    parameters: {
      query?: never
      header?: never
      path: {
        revision_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RevisionTransition']
        'application/x-www-form-urlencoded': components['schemas']['RevisionTransition']
        'multipart/form-data': components['schemas']['RevisionTransition']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EditorialRevision']
        }
      }
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EditorialWorkflowError']
        }
      }
    }
  }
  commitCatalogCsv: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['CatalogCsvCommitRequest']
        'application/x-www-form-urlencoded': components['schemas']['CatalogCsvCommitRequest']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CatalogImportCommitResponse']
        }
      }
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CatalogImportCommitResponse']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CatalogImportCommitError']
        }
      }
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CatalogImportCommitError']
        }
      }
    }
  }
  validateCatalogCsv: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['CatalogCsvValidationRequest']
        'application/x-www-form-urlencoded': components['schemas']['CatalogCsvValidationRequest']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CatalogCsvValidationResponse']
        }
      }
    }
  }
  api_v1_admin_reports_list: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdminReport'][]
        }
      }
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            detail?: string
          }
        }
      }
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            detail?: string
          }
        }
      }
    }
  }
  api_v1_admin_reports_partial_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        report_id: string
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedAdminReport']
        'application/x-www-form-urlencoded': components['schemas']['PatchedAdminReport']
        'multipart/form-data': components['schemas']['PatchedAdminReport']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdminReport']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            detail?: string
          }
        }
      }
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            detail?: string
          }
        }
      }
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            detail?: string
          }
        }
      }
    }
  }
  api_v1_events_batch_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AnalyticsBatch']
        'application/x-www-form-urlencoded': components['schemas']['AnalyticsBatch']
        'multipart/form-data': components['schemas']['AnalyticsBatch']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            received?: number
            status?: string
          }
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            detail?: string
          }
        }
      }
    }
  }
  api_v1_health_retrieve: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            status?: string
          }
        }
      }
    }
  }
  api_v1_public_reports_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PublicReportCreate']
        'application/x-www-form-urlencoded': components['schemas']['PublicReportCreate']
        'multipart/form-data': components['schemas']['PublicReportCreate']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PublicReportCreatedResponse']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            detail?: string
          }
        }
      }
    }
  }
  listPublishedRegions: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RegionSummary'][]
        }
      }
    }
  }
  listPublishedRegionRoutes: {
    parameters: {
      query?: never
      header?: never
      path: {
        region_slug: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RouteSummary'][]
        }
      }
    }
  }
  retrievePublishedRoute: {
    parameters: {
      query?: never
      header?: never
      path: {
        region_slug: string
        route_slug: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RouteDetail']
        }
      }
    }
  }
  listPublishedRouteCatalog: {
    parameters: {
      query?: never
      header?: never
      path: {
        region_slug: string
        route_slug: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RouteCatalogItem'][]
        }
      }
    }
  }
  api_v1_schema_retrieve: {
    parameters: {
      query?: {
        format?: 'json' | 'yaml'
        lang?:
          | 'af'
          | 'ar'
          | 'ar-dz'
          | 'ast'
          | 'az'
          | 'be'
          | 'bg'
          | 'bn'
          | 'br'
          | 'bs'
          | 'ca'
          | 'ckb'
          | 'cs'
          | 'cy'
          | 'da'
          | 'de'
          | 'dsb'
          | 'el'
          | 'en'
          | 'en-au'
          | 'en-gb'
          | 'eo'
          | 'es'
          | 'es-ar'
          | 'es-co'
          | 'es-mx'
          | 'es-ni'
          | 'es-ve'
          | 'et'
          | 'eu'
          | 'fa'
          | 'fi'
          | 'fr'
          | 'fy'
          | 'ga'
          | 'gd'
          | 'gl'
          | 'he'
          | 'hi'
          | 'hr'
          | 'hsb'
          | 'hu'
          | 'hy'
          | 'ia'
          | 'id'
          | 'ig'
          | 'io'
          | 'is'
          | 'it'
          | 'ja'
          | 'ka'
          | 'kab'
          | 'kk'
          | 'km'
          | 'kn'
          | 'ko'
          | 'ky'
          | 'lb'
          | 'lt'
          | 'lv'
          | 'mk'
          | 'ml'
          | 'mn'
          | 'mr'
          | 'ms'
          | 'my'
          | 'nb'
          | 'ne'
          | 'nl'
          | 'nn'
          | 'os'
          | 'pa'
          | 'pl'
          | 'pt'
          | 'pt-br'
          | 'ro'
          | 'ru'
          | 'sk'
          | 'sl'
          | 'sq'
          | 'sr'
          | 'sr-latn'
          | 'sv'
          | 'sw'
          | 'ta'
          | 'te'
          | 'tg'
          | 'th'
          | 'tk'
          | 'tr'
          | 'tt'
          | 'udm'
          | 'ug'
          | 'uk'
          | 'ur'
          | 'uz'
          | 'vi'
          | 'zh-hans'
          | 'zh-hant'
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/vnd.oai.openapi': {
            [key: string]: unknown
          }
          'application/yaml': {
            [key: string]: unknown
          }
          'application/vnd.oai.openapi+json': {
            [key: string]: unknown
          }
          'application/json': {
            [key: string]: unknown
          }
        }
      }
    }
  }
}
