# Generated by Django 5.2.16 on 2026-07-29 12:27

import uuid

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("public_name", models.CharField(max_length=160)),
                ("short_description", models.CharField(blank=True, max_length=300)),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "center_point",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                (
                    "timezone",
                    models.CharField(default="America/Fortaleza", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("review", "Em revisão"),
                            ("approved", "Aprovado"),
                            ("published", "Publicado"),
                            ("suspended", "Suspenso"),
                            ("archived", "Arquivado"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "published_version",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "ordering": ("public_name",),
                "indexes": [
                    models.Index(fields=["status", "public_name"], name="region_status_name_idx")
                ],
            },
        ),
    ]
