# Generated by Django 5.2.16 on 2026-07-29 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publishing", "0002_publication_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicationversion",
            name="restored_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="restorations",
                to="publishing.publicationversion",
            ),
        ),
        migrations.AlterField(
            model_name="publicationversion",
            name="revision",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="publication",
                to="publishing.editorialrevision",
            ),
        ),
    ]
