# Generated by Django 5.2.16 on 2026-07-31 19:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawAnalyticsEvent",
            fields=[
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_name", models.CharField(db_index=True, max_length=64)),
                ("schema_version", models.CharField(default="1.0", max_length=16)),
                ("occurred_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("anonymous_id", models.UUIDField(db_index=True)),
                ("session_id", models.UUIDField(blank=True, null=True)),
                ("consent_id", models.UUIDField(blank=True, null=True)),
                ("consent_version", models.CharField(default="1.0", max_length=16)),
                ("app_version", models.CharField(default="1.0.0", max_length=32)),
                ("screen_name", models.CharField(blank=True, max_length=64)),
                (
                    "region_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "route_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("actor_id", models.CharField(blank=True, max_length=64)),
                ("stage_id", models.CharField(blank=True, max_length=64)),
                ("source", models.CharField(blank=True, max_length=64)),
                ("campaign_id", models.CharField(blank=True, max_length=64)),
                ("device_class", models.CharField(blank=True, max_length=32)),
                ("network_class", models.CharField(blank=True, max_length=32)),
                ("display_mode", models.CharField(blank=True, max_length=32)),
                ("properties", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Evento Bruto de Analytics",
                "verbose_name_plural": "Eventos Brutos de Analytics",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyAnalyticsAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("event_name", models.CharField(db_index=True, max_length=64)),
                (
                    "region_slug",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "route_slug",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Agregação Diária de Analytics",
                "verbose_name_plural": "Agregações Diárias de Analytics",
                "ordering": ["-date", "event_name"],
                "unique_together": {("date", "event_name", "region_slug", "route_slug")},
            },
        ),
    ]
