# Generated by Django 5.2.16 on 2026-07-29 12:27

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=120)),
                ("public_name", models.CharField(max_length=160)),
                ("short_promise", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("duration_minutes", models.PositiveIntegerField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Fácil"),
                            ("moderate", "Moderada"),
                            ("hard", "Difícil"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "estimated_cost_min",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "estimated_cost_max",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("transport_modes", models.JSONField(blank=True, default=list)),
                ("preparation_content", models.TextField(blank=True)),
                ("accessibility_content", models.TextField(blank=True)),
                ("offline_enabled", models.BooleanField(default=False)),
                (
                    "editorial_status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("review", "Em revisão"),
                            ("approved", "Aprovado"),
                            ("published", "Publicado"),
                            ("suspended", "Suspenso"),
                            ("archived", "Arquivado"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routes",
                        to="regions.region",
                    ),
                ),
            ],
            options={
                "ordering": ("region_id", "public_name"),
            },
        ),
        migrations.CreateModel(
            name="RouteStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveSmallIntegerField()),
                ("public_name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("point", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("arrival_guidance", models.TextField(blank=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "stage_type",
                    models.CharField(
                        choices=[
                            ("start", "Início"),
                            ("stop", "Parada"),
                            ("experience", "Experiência"),
                            ("support", "Apoio"),
                            ("end", "Fim"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_optional", models.BooleanField(default=False)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="routes.route",
                    ),
                ),
            ],
            options={
                "ordering": ("route_id", "position"),
            },
        ),
        migrations.CreateModel(
            name="RouteSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.LineStringField(srid=4326),
                ),
                ("transport_mode", models.CharField(max_length=32)),
                ("distance_meters", models.PositiveIntegerField()),
                ("duration_minutes", models.PositiveIntegerField()),
                ("instructions", models.TextField(blank=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="routes.route",
                    ),
                ),
                (
                    "from_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_segments",
                        to="routes.routestage",
                    ),
                ),
                (
                    "to_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_segments",
                        to="routes.routestage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Informativo"),
                            ("warning", "Atenção"),
                            ("critical", "Crítico"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField()),
                ("alternative", models.TextField(blank=True)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("review", "Em revisão"),
                            ("approved", "Aprovado"),
                            ("published", "Publicado"),
                            ("suspended", "Suspenso"),
                            ("archived", "Arquivado"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="regions.region",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="routes.route",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="routes.routestage",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["region", "editorial_status"], name="route_region_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="route",
            constraint=models.UniqueConstraint(
                fields=("region", "slug"), name="route_region_slug_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="route",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_minutes__gt", 0)),
                name="route_duration_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="route",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("estimated_cost_min__isnull", True),
                    ("estimated_cost_max__isnull", True),
                    ("estimated_cost_max__gte", models.F("estimated_cost_min")),
                    _connector="OR",
                ),
                name="route_cost_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="routestage",
            constraint=models.UniqueConstraint(
                fields=("route", "position"), name="stage_route_position_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="routestage",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gt", 0)), name="stage_position_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="routestage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("duration_minutes__isnull", True),
                    ("duration_minutes__gt", 0),
                    _connector="OR",
                ),
                name="stage_duration_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="routesegment",
            constraint=models.UniqueConstraint(
                fields=("route", "from_stage", "to_stage"), name="segment_path_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="routesegment",
            constraint=models.CheckConstraint(
                condition=models.Q(("from_stage", models.F("to_stage")), _negated=True),
                name="segment_distinct_stages",
            ),
        ),
        migrations.AddConstraint(
            model_name="routesegment",
            constraint=models.CheckConstraint(
                condition=models.Q(("distance_meters__gt", 0)),
                name="segment_distance_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="routesegment",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_minutes__gt", 0)),
                name="segment_duration_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["region", "status", "severity"], name="alert_region_state_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="alert",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ends_at__isnull", True),
                    ("ends_at__gt", models.F("starts_at")),
                    _connector="OR",
                ),
                name="alert_period_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="alert",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("stage__isnull", True), ("route__isnull", False), _connector="OR"
                ),
                name="alert_stage_requires_route",
            ),
        ),
    ]
