# Generated by Django 5.2.16 on 2026-07-29 12:27

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("regions", "0001_initial"),
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=160, unique=True)),
                (
                    "actor_kind",
                    models.CharField(
                        choices=[
                            ("business", "Empresa"),
                            ("individual_provider", "Prestador individual"),
                            ("community", "Comunidade"),
                            ("institution", "Instituição"),
                            ("support", "Ponto de apoio"),
                        ],
                        max_length=24,
                    ),
                ),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("public_name", models.CharField(max_length=160)),
                ("legal_name", models.CharField(blank=True, max_length=200)),
                ("short_description", models.CharField(max_length=180)),
                ("full_description", models.TextField(blank=True)),
                ("services", models.JSONField(blank=True, default=list)),
                (
                    "editorial_status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("review", "Em revisão"),
                            ("approved", "Aprovado"),
                            ("published", "Publicado"),
                            ("suspended", "Suspenso"),
                            ("archived", "Arquivado"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "partnership_type",
                    models.CharField(
                        choices=[
                            ("editorial", "Editorial"),
                            ("partner", "Parceiro"),
                            ("sponsored", "Patrocinado"),
                        ],
                        default="editorial",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ("public_name",),
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("public_name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ("public_name",),
            },
        ),
        migrations.CreateModel(
            name="ActorLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=120)),
                ("address_fields", models.JSONField(blank=True, default=dict)),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "service_area",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("public_visibility", models.BooleanField(default=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="catalog.actor",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actor_locations",
                        to="regions.region",
                    ),
                ),
            ],
            options={
                "ordering": ("actor_id", "-is_primary", "label"),
            },
        ),
        migrations.AddField(
            model_name="actor",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actors",
                to="catalog.category",
            ),
        ),
        migrations.CreateModel(
            name="ContactChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("phone", "Telefone"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "E-mail"),
                            ("website", "Site"),
                            ("instagram", "Instagram"),
                        ],
                        max_length=16,
                    ),
                ),
                ("value_encrypted", models.TextField(blank=True)),
                ("public_value", models.CharField(blank=True, max_length=500)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "authorization_reference",
                    models.CharField(blank=True, max_length=200),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_channels",
                        to="catalog.actor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperatingHours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("weekday", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("opens_at", models.TimeField(blank=True, null=True)),
                ("closes_at", models.TimeField(blank=True, null=True)),
                ("is_closed", models.BooleanField(default=False)),
                ("exception_date", models.DateField(blank=True, null=True)),
                ("public_note", models.CharField(blank=True, max_length=240)),
                (
                    "actor_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operating_hours",
                        to="catalog.actorlocation",
                    ),
                ),
            ],
            options={
                "ordering": ("actor_location_id", "exception_date", "weekday"),
            },
        ),
        migrations.CreateModel(
            name="RouteActor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "route_role",
                    models.CharField(
                        choices=[
                            ("experience", "Experiência"),
                            ("support", "Apoio"),
                            ("start", "Início"),
                            ("stop", "Parada"),
                            ("emergency", "Emergência"),
                            ("service", "Serviço"),
                        ],
                        max_length=16,
                    ),
                ),
                ("editorial_position", models.PositiveSmallIntegerField(default=1)),
                ("is_featured", models.BooleanField(default=False)),
                ("sponsorship_label", models.CharField(blank=True, max_length=160)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_links",
                        to="catalog.actor",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actor_links",
                        to="routes.route",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actor_links",
                        to="routes.routestage",
                    ),
                ),
            ],
            options={
                "ordering": ("route_id", "editorial_position", "actor_id"),
            },
        ),
        migrations.AddIndex(
            model_name="actorlocation",
            index=models.Index(
                fields=["region", "public_visibility"],
                name="location_region_public_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="actorlocation",
            constraint=models.UniqueConstraint(
                fields=("actor", "region", "label"),
                name="location_actor_region_label_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="actorlocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("actor", "region"),
                name="location_one_primary_per_region",
            ),
        ),
        migrations.AddIndex(
            model_name="actor",
            index=models.Index(
                fields=["category", "editorial_status"], name="actor_category_state_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contactchannel",
            constraint=models.UniqueConstraint(
                fields=("actor", "channel_type", "public_value"),
                name="contact_public_channel_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactchannel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_public", False),
                    models.Q(("public_value__gt", ""), ("authorization_reference__gt", "")),
                    _connector="OR",
                ),
                name="contact_public_requires_authorization",
            ),
        ),
        migrations.AddConstraint(
            model_name="operatinghours",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("weekday__isnull", True),
                    ("weekday__range", (0, 6)),
                    _connector="OR",
                ),
                name="hours_weekday_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="operatinghours",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("exception_date__isnull", False),
                    ("weekday__isnull", False),
                    _connector="OR",
                ),
                name="hours_day_or_exception",
            ),
        ),
        migrations.AddConstraint(
            model_name="operatinghours",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_closed", True),
                    models.Q(("opens_at__isnull", False), ("closes_at__isnull", False)),
                    _connector="OR",
                ),
                name="hours_open_requires_times",
            ),
        ),
        migrations.AddConstraint(
            model_name="routeactor",
            constraint=models.UniqueConstraint(
                fields=("route", "actor", "stage", "route_role"),
                name="route_actor_context_uniq",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="routeactor",
            constraint=models.CheckConstraint(
                condition=models.Q(("editorial_position__gt", 0)),
                name="route_actor_position_positive",
            ),
        ),
    ]
